<?php
/**
 * GENERATED by bin/palette-build.php from bin/palette-sources.json. Do not edit by hand.
 */

return array (
  'atelier' => 
  array (
    'name' => 'Atelier',
    'default' => true,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#271d1b',
      1 => '#c99091',
      2 => '#b99a72',
      3 => '#e9d5cc',
      4 => '#f8f4f0',
    ),
    'slots' => 
    array (
      'ivory' => '#f8f4f0',
      'porcelain' => '#fffdfb',
      'linen' => '#f1e6df',
      'nude' => '#e9d5cc',
      'rose' => '#c99091',
      'rose-ink' => '#8f585a',
      'champagne' => '#b99a72',
      'champagne-ink' => '#85683f',
      'espresso' => '#271d1b',
      'cocoa' => '#5e4b45',
      'taupe' => '#6f5c56',
      'on-rose' => '#271d1b',
      'rose-glow' => '#c99091',
      'rose-card' => '#bc8788',
      'rose-muted' => '#372827',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'fixed: the approved Maison Élise colours',
    ),
  ),
  'elite-signature' => 
  array (
    'name' => 'Elite Signature',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0b0b0b',
      1 => '#10211d',
      2 => '#c9a86a',
      3 => '#e7ddcf',
      4 => '#f5f0e6',
    ),
    'slots' => 
    array (
      'ivory' => '#f5f0e6',
      'porcelain' => '#fbf9f5',
      'linen' => '#efe7dc',
      'nude' => '#e7ddcf',
      'rose' => '#c9a86a',
      'rose-ink' => '#796642',
      'champagne' => '#d8c195',
      'champagne-ink' => '#726650',
      'espresso' => '#0b0b0b',
      'cocoa' => '#10211d',
      'taupe' => '#5e6761',
      'on-rose' => '#0b0b0b',
      'rose-glow' => '#c9a86a',
      'rose-card' => '#ba9b62',
      'rose-muted' => '#3c3424',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.50)',
    ),
  ),
  'gilded-noir' => 
  array (
    'name' => 'Gilded Noir',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0b0b0f',
      1 => '#d4af37',
      2 => '#f5f0e6',
      3 => '#3b3a40',
      4 => '#8a6f3a',
    ),
    'slots' => 
    array (
      'ivory' => '#f5f0e6',
      'porcelain' => '#fbf9f5',
      'linen' => '#efe9dd',
      'nude' => '#e8e1d1',
      'rose' => '#d4af37',
      'rose-ink' => '#7c6725',
      'champagne' => '#e0c674',
      'champagne-ink' => '#71653f',
      'espresso' => '#0b0b0f',
      'cocoa' => '#3b3a40',
      'taupe' => '#6b696b',
      'on-rose' => '#0b0b0f',
      'rose-glow' => '#d4af37',
      'rose-card' => '#c4a234',
      'rose-muted' => '#43391a',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.44)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.52)',
    ),
  ),
  'champagne-pearl' => 
  array (
    'name' => 'Champagne Pearl',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#f7e7ce',
      1 => '#ead9c3',
      2 => '#c8b7a6',
      3 => '#9b8f84',
      4 => '#2c2a28',
    ),
    'slots' => 
    array (
      'ivory' => '#f7e7ce',
      'porcelain' => '#fcf5eb',
      'linen' => '#f1e1c9',
      'nude' => '#ead9c3',
      'rose' => '#c8b7a6',
      'rose-ink' => '#6a625a',
      'champagne' => '#d8c8b4',
      'champagne-ink' => '#6a635a',
      'espresso' => '#2c2a28',
      'cocoa' => '#6a635c',
      'taupe' => '#6a635c',
      'on-rose' => '#2c2a28',
      'rose-glow' => '#c8b7a6',
      'rose-card' => '#bcac9c',
      'rose-muted' => '#45413c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'cocoa: depth darkened to read as text (push 0.44)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.60)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.64)',
    ),
  ),
  'emerald-velvet' => 
  array (
    'name' => 'Emerald Velvet',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0e3b2e',
      1 => '#1f6f54',
      2 => '#c9a227',
      3 => '#f2e8d8',
      4 => '#1b1b1d',
    ),
    'slots' => 
    array (
      'ivory' => '#f2e8d8',
      'porcelain' => '#faf6ef',
      'linen' => '#e7e1d1',
      'nude' => '#d9d9c8',
      'rose' => '#c9a227',
      'rose-ink' => '#756122',
      'champagne' => '#d7bb65',
      'champagne-ink' => '#6e613d',
      'espresso' => '#1b1b1d',
      'cocoa' => '#0e3b2e',
      'taupe' => '#49685a',
      'on-rose' => '#1b1b1d',
      'rose-glow' => '#c9a227',
      'rose-card' => '#bb9726',
      'rose-muted' => '#3a331f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.48)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.56)',
    ),
  ),
  'sapphire-lounge' => 
  array (
    'name' => 'Sapphire Lounge',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0b1b3a',
      1 => '#1e3a8a',
      2 => '#a1b2d6',
      3 => '#e7e2d9',
      4 => '#b48a5a',
    ),
    'slots' => 
    array (
      'ivory' => '#e9e5dd',
      'porcelain' => '#f6f5f1',
      'linen' => '#e5e2dd',
      'nude' => '#e0dfdc',
      'rose' => '#b48a5a',
      'rose-ink' => '#74604e',
      'champagne' => '#c6a986',
      'champagne-ink' => '#696260',
      'espresso' => '#0b1b3a',
      'cocoa' => '#1e3a8a',
      'taupe' => '#4f639e',
      'on-rose' => '#0b1b3a',
      'rose-glow' => '#b48a5a',
      'rose-card' => '#a68157',
      'rose-muted' => '#121f3b',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.10)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.38)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.50)',
    ),
  ),
  'rose-gold-dusk' => 
  array (
    'name' => 'Rose Gold Dusk',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#b76e79',
      1 => '#e6c2c6',
      2 => '#6b4e5e',
      3 => '#f6efe8',
      4 => '#1f1c1e',
    ),
    'slots' => 
    array (
      'ivory' => '#f6efe8',
      'porcelain' => '#fbf9f6',
      'linen' => '#efdbd9',
      'nude' => '#e6c2c6',
      'rose' => '#b76e79',
      'rose-ink' => '#86545c',
      'champagne' => '#cd9ba0',
      'champagne-ink' => '#765c5f',
      'espresso' => '#1f1c1e',
      'cocoa' => '#6b4e5e',
      'taupe' => '#765b69',
      'on-rose' => '#1d1a1c',
      'rose-glow' => '#c2858d',
      'rose-card' => '#ab6772',
      'rose-muted' => '#1d1a1c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.32)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.50)',
      2 => 'on-rose: label pushed to read on the accent (push 0.06)',
      3 => 'rose-glow: accent lightened for text on dark surfaces (push 0.18)',
    ),
  ),
  'mocha-silk' => 
  array (
    'name' => 'Mocha Silk',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#4b2e2a',
      1 => '#7a5645',
      2 => '#c6a58d',
      3 => '#efe3d6',
      4 => '#1e1a18',
    ),
    'slots' => 
    array (
      'ivory' => '#efe3d6',
      'porcelain' => '#f9f4ef',
      'linen' => '#e9dbce',
      'nude' => '#e1d2c5',
      'rose' => '#c6a58d',
      'rose-ink' => '#6f5d50',
      'champagne' => '#d4bba7',
      'champagne-ink' => '#6a5e54',
      'espresso' => '#1e1a18',
      'cocoa' => '#4b2e2a',
      'taupe' => '#725953',
      'on-rose' => '#1e1a18',
      'rose-glow' => '#c6a58d',
      'rose-card' => '#b99a84',
      'rose-muted' => '#3c332d',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.52)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.58)',
    ),
  ),
  'ivory-marble' => 
  array (
    'name' => 'Ivory Marble',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#f8f6f1',
      1 => '#d8d2c8',
      2 => '#afa79c',
      3 => '#5b5a57',
      4 => '#121212',
    ),
    'slots' => 
    array (
      'ivory' => '#f8f6f1',
      'porcelain' => '#fcfbf9',
      'linen' => '#eae6df',
      'nude' => '#d8d2c8',
      'rose' => '#afa79c',
      'rose-ink' => '#6a655f',
      'champagne' => '#c9c3ba',
      'champagne-ink' => '#6a6763',
      'espresso' => '#121212',
      'cocoa' => '#5b5a57',
      'taupe' => '#686663',
      'on-rose' => '#121212',
      'rose-glow' => '#afa79c',
      'rose-card' => '#a29b91',
      'rose-muted' => '#353330',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.44)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.52)',
    ),
  ),
  'plum-regent' => 
  array (
    'name' => 'Plum Regent',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#3a0d2c',
      1 => '#6a1b4d',
      2 => '#d9b1c7',
      3 => '#f3e6ef',
      4 => '#c6a24b',
    ),
    'slots' => 
    array (
      'ivory' => '#f3e6ef',
      'porcelain' => '#faf5f9',
      'linen' => '#f2e3ed',
      'nude' => '#f0e0ea',
      'rose' => '#c6a24b',
      'rose-ink' => '#865d3d',
      'champagne' => '#d6ba84',
      'champagne-ink' => '#825d54',
      'espresso' => '#3a0d2c',
      'cocoa' => '#6a1b4d',
      'taupe' => '#90547a',
      'on-rose' => '#3a0d2c',
      'rose-glow' => '#c6a24b',
      'rose-card' => '#bb9649',
      'rose-muted' => '#502531',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.46)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.54)',
    ),
  ),
  'copper-cashmere' => 
  array (
    'name' => 'Copper Cashmere',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#8c4a2f',
      1 => '#c07a55',
      2 => '#e7c6b0',
      3 => '#f7f2ec',
      4 => '#2b2320',
    ),
    'slots' => 
    array (
      'ivory' => '#f7f2ec',
      'porcelain' => '#fcfaf7',
      'linen' => '#f0ded1',
      'nude' => '#e7c6b0',
      'rose' => '#c07a55',
      'rose-ink' => '#875941',
      'champagne' => '#d3a48a',
      'champagne-ink' => '#785e51',
      'espresso' => '#2b2320',
      'cocoa' => '#8c4a2f',
      'taupe' => '#92543a',
      'on-rose' => '#2b2320',
      'rose-glow' => '#cb9273',
      'rose-card' => '#b47351',
      'rose-muted' => '#2b2320',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.38)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.54)',
      2 => 'rose-glow: accent lightened for text on dark surfaces (push 0.20)',
    ),
  ),
  'midnight-orchid' => 
  array (
    'name' => 'Midnight Orchid',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#120b1a',
      1 => '#2b1b3d',
      2 => '#7a5c9e',
      3 => '#e7d9f2',
      4 => '#bfa36a',
    ),
    'slots' => 
    array (
      'ivory' => '#ece1f5',
      'porcelain' => '#f7f3fb',
      'linen' => '#e6daf1',
      'nude' => '#ded1eb',
      'rose' => '#bfa36a',
      'rose-ink' => '#6f5d45',
      'champagne' => '#cdb69a',
      'champagne-ink' => '#6c5d57',
      'espresso' => '#120b1a',
      'cocoa' => '#2b1b3d',
      'taupe' => '#695a78',
      'on-rose' => '#120b1a',
      'rose-glow' => '#bfa36a',
      'rose-card' => '#b19764',
      'rose-muted' => '#3c2f2d',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.20)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.46)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.52)',
    ),
  ),
  'caviar-cream' => 
  array (
    'name' => 'Caviar & Cream',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0f0f10',
      1 => '#2a2a2d',
      2 => '#c9c2b8',
      3 => '#f4f1eb',
      4 => '#a88f5a',
    ),
    'slots' => 
    array (
      'ivory' => '#f4f1eb',
      'porcelain' => '#fbf9f7',
      'linen' => '#f2eee8',
      'nude' => '#efebe5',
      'rose' => '#a88f5a',
      'rose-ink' => '#7a6944',
      'champagne' => '#c3b18d',
      'champagne-ink' => '#746a56',
      'espresso' => '#0f0f10',
      'cocoa' => '#2a2a2d',
      'taupe' => '#6b6a6a',
      'on-rose' => '#0f0f10',
      'rose-glow' => '#a88f5a',
      'rose-card' => '#9c8554',
      'rose-muted' => '#24211a',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.30)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.44)',
    ),
  ),
  'forest-reserve' => 
  array (
    'name' => 'Forest Reserve',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#102a24',
      1 => '#2f5d50',
      2 => '#9e8b5a',
      3 => '#efe6d6',
      4 => '#3a2f2a',
    ),
    'slots' => 
    array (
      'ivory' => '#efe6d6',
      'porcelain' => '#f9f5ef',
      'linen' => '#e5dccd',
      'nude' => '#d9d0c1',
      'rose' => '#9e8b5a',
      'rose-ink' => '#626243',
      'champagne' => '#baab85',
      'champagne-ink' => '#5b634f',
      'espresso' => '#102a24',
      'cocoa' => '#2f5d50',
      'taupe' => '#3e685b',
      'on-rose' => '#102a24',
      'rose-glow' => '#ad9b70',
      'rose-card' => '#938356',
      'rose-muted' => '#102a24',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.56)',
      2 => 'rose-glow: accent lightened for text on dark surfaces (push 0.18)',
    ),
  ),
  'antique-brocade' => 
  array (
    'name' => 'Antique Brocade',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#3e2c1c',
      1 => '#7b5e3b',
      2 => '#c2a77d',
      3 => '#ede3cf',
      4 => '#5c2e2e',
    ),
    'slots' => 
    array (
      'ivory' => '#ede4d0',
      'porcelain' => '#f8f4ec',
      'linen' => '#e7ddc8',
      'nude' => '#dfd4be',
      'rose' => '#c2a77d',
      'rose-ink' => '#735d43',
      'champagne' => '#d1bc9a',
      'champagne-ink' => '#705d47',
      'espresso' => '#3e2c1c',
      'cocoa' => '#5c2e2e',
      'taupe' => '#7c5652',
      'on-rose' => '#3e2c1c',
      'rose-glow' => '#c2a77d',
      'rose-card' => '#b79d75',
      'rose-muted' => '#463322',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.02)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.60)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.66)',
    ),
  ),
  'slate-penthouse' => 
  array (
    'name' => 'Slate Penthouse',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#1c1f24',
      1 => '#3a4452',
      2 => '#9aa3ad',
      3 => '#f2eee7',
      4 => '#c79c5a',
    ),
    'slots' => 
    array (
      'ivory' => '#f2eee7',
      'porcelain' => '#faf8f5',
      'linen' => '#edeae4',
      'nude' => '#e7e5e0',
      'rose' => '#c79c5a',
      'rose-ink' => '#7c6542',
      'champagne' => '#d6b98b',
      'champagne-ink' => '#726653',
      'espresso' => '#1c1f24',
      'cocoa' => '#3a4452',
      'taupe' => '#626973',
      'on-rose' => '#1c1f24',
      'rose-glow' => '#c79c5a',
      'rose-card' => '#b99256',
      'rose-muted' => '#34302c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.44)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.54)',
    ),
  ),
  'desert-luxe' => 
  array (
    'name' => 'Desert Luxe',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#d8c3a5',
      1 => '#bfa38a',
      2 => '#8c6a4a',
      3 => '#f6f1e8',
      4 => '#2a2320',
    ),
    'slots' => 
    array (
      'ivory' => '#f6f1e8',
      'porcelain' => '#fbf9f6',
      'linen' => '#e9dcca',
      'nude' => '#d8c3a5',
      'rose' => '#bfa38a',
      'rose-ink' => '#6f5e51',
      'champagne' => '#d2beab',
      'champagne-ink' => '#6a5e55',
      'espresso' => '#2a2320',
      'cocoa' => '#785c42',
      'taupe' => '#785c42',
      'on-rose' => '#2a2320',
      'rose-glow' => '#bfa38a',
      'rose-card' => '#b39982',
      'rose-muted' => '#3c322d',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'cocoa: depth darkened to read as text (push 0.20)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.54)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.62)',
    ),
  ),
  'garnet-gala' => 
  array (
    'name' => 'Garnet Gala',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#4a0e16',
      1 => '#8e1b2f',
      2 => '#d7b9a6',
      3 => '#f4ece6',
      4 => '#c3a14a',
    ),
    'slots' => 
    array (
      'ivory' => '#f4ece6',
      'porcelain' => '#fbf7f5',
      'linen' => '#f3e9e2',
      'nude' => '#f1e6de',
      'rose' => '#c3a14a',
      'rose-ink' => '#8e6033',
      'champagne' => '#d4bb81',
      'champagne-ink' => '#895e47',
      'espresso' => '#4a0e16',
      'cocoa' => '#8e1b2f',
      'taupe' => '#a64d5b',
      'on-rose' => '#4a0e16',
      'rose-glow' => '#c3a14a',
      'rose-card' => '#b99546',
      'rose-muted' => '#59201c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.44)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.54)',
    ),
  ),
  'ocean-suite' => 
  array (
    'name' => 'Ocean Suite',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0e2a3a',
      1 => '#1b4d5c',
      2 => '#7fa6a8',
      3 => '#f1efe8',
      4 => '#b08a57',
    ),
    'slots' => 
    array (
      'ivory' => '#f1efe8',
      'porcelain' => '#f9f9f6',
      'linen' => '#ebebe4',
      'nude' => '#e3e6e0',
      'rose' => '#b08a57',
      'rose-ink' => '#76674d',
      'champagne' => '#c7ad8a',
      'champagne-ink' => '#676960',
      'espresso' => '#0e2a3a',
      'cocoa' => '#1b4d5c',
      'taupe' => '#466d78',
      'on-rose' => '#0e2a3a',
      'rose-glow' => '#ba9a6e',
      'rose-card' => '#a38255',
      'rose-muted' => '#0e2a3a',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.36)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.52)',
      2 => 'rose-glow: accent lightened for text on dark surfaces (push 0.16)',
    ),
  ),
  'olive-atelier' => 
  array (
    'name' => 'Olive Atelier',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#2b3a2f',
      1 => '#556b2f',
      2 => '#c1b08a',
      3 => '#f3eee2',
      4 => '#3c2f2a',
    ),
    'slots' => 
    array (
      'ivory' => '#f3eee2',
      'porcelain' => '#faf8f3',
      'linen' => '#e9e4d8',
      'nude' => '#ddd7cc',
      'rose' => '#c1b08a',
      'rose-ink' => '#646752',
      'champagne' => '#d3c6a9',
      'champagne-ink' => '#616756',
      'espresso' => '#2b3a2f',
      'cocoa' => '#556b2f',
      'taupe' => '#556b2f',
      'on-rose' => '#2b3a2f',
      'rose-glow' => '#c1b08a',
      'rose-card' => '#b5a783',
      'rose-muted' => '#344134',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.62)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.68)',
    ),
  ),
  'pewter-regency' => 
  array (
    'name' => 'Pewter Regency',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#2e3136',
      1 => '#6b7078',
      2 => '#b8b0a6',
      3 => '#f5f2ec',
      4 => '#d1b27c',
    ),
    'slots' => 
    array (
      'ivory' => '#f5f2ec',
      'porcelain' => '#fbfaf7',
      'linen' => '#f2eee8',
      'nude' => '#eeeae4',
      'rose' => '#d1b27c',
      'rose-ink' => '#766a55',
      'champagne' => '#dec8a3',
      'champagne-ink' => '#716a5f',
      'espresso' => '#2e3136',
      'cocoa' => '#676c74',
      'taupe' => '#676c74',
      'on-rose' => '#2e3136',
      'rose-glow' => '#d1b27c',
      'rose-card' => '#c4a876',
      'rose-muted' => '#42403e',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'cocoa: depth darkened to read as text (push 0.06)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.56)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.62)',
    ),
  ),
  'sunlit-terrace' => 
  array (
    'name' => 'Sunlit Terrace',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#f6e7d8',
      1 => '#e8c39e',
      2 => '#c98b5c',
      3 => '#6b4b3a',
      4 => '#1e1a18',
    ),
    'slots' => 
    array (
      'ivory' => '#f6e7d8',
      'porcelain' => '#fbf5ef',
      'linen' => '#f0d7be',
      'nude' => '#e8c39e',
      'rose' => '#c98b5c',
      'rose-ink' => '#7a573d',
      'champagne' => '#d9ab87',
      'champagne-ink' => '#705a49',
      'espresso' => '#1e1a18',
      'cocoa' => '#6b4b3a',
      'taupe' => '#765747',
      'on-rose' => '#1e1a18',
      'rose-glow' => '#c98b5c',
      'rose-card' => '#bb8257',
      'rose-muted' => '#2f251f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.46)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.56)',
    ),
  ),
  'refined-elegance' => 
  array (
    'name' => 'Refined Elegance',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#cdcbc8',
      1 => '#b9b8ae',
      2 => '#17181b',
      3 => '#646b3c',
      4 => '#bbb9b7',
    ),
    'slots' => 
    array (
      'ivory' => '#e6e5e4',
      'porcelain' => '#f5f5f4',
      'linen' => '#e4e3e2',
      'nude' => '#e1e0df',
      'rose' => '#b9b8ae',
      'rose-ink' => '#656562',
      'champagne' => '#c0bfb7',
      'champagne-ink' => '#656563',
      'espresso' => '#17181b',
      'cocoa' => '#62693b',
      'taupe' => '#62693b',
      'on-rose' => '#17181b',
      'rose-glow' => '#b9b8ae',
      'rose-card' => '#acaba2',
      'rose-muted' => '#3e3e3e',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.50)',
      1 => 'cocoa: depth darkened to read as text (push 0.02)',
      2 => 'rose-ink: accent darkened for text on light surfaces (push 0.52)',
      3 => 'champagne-ink: darkened for text on light surfaces (push 0.54)',
    ),
  ),
  'enchanted-nature' => 
  array (
    'name' => 'Enchanted Nature',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#132b57',
      1 => '#4b6730',
      2 => '#3e5d65',
      3 => '#9d7312',
      4 => '#f3eee3',
    ),
    'slots' => 
    array (
      'ivory' => '#f3eee3',
      'porcelain' => '#faf8f4',
      'linen' => '#e9e6dc',
      'nude' => '#ddddd4',
      'rose' => '#9d7312',
      'rose-ink' => '#7f6321',
      'champagne' => '#bea363',
      'champagne-ink' => '#69675d',
      'espresso' => '#132b57',
      'cocoa' => '#4b6730',
      'taupe' => '#556f3b',
      'on-rose' => '#060e1c',
      'rose-glow' => '#bea261',
      'rose-card' => '#916b13',
      'rose-muted' => '#060e1c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.22)',
      1 => 'champagne: lightened for text on dark surfaces (push 0.06)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.50)',
      3 => 'on-rose: label pushed to read on the accent (push 0.68)',
      4 => 'rose-glow: accent lightened for text on dark surfaces (push 0.38)',
    ),
  ),
  'monochromatic-blues' => 
  array (
    'name' => 'Monochromatic Blues',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#124a97',
      1 => '#167bb6',
      2 => '#7fc3d4',
      3 => '#abced9',
      4 => '#071e3c',
    ),
    'slots' => 
    array (
      'ivory' => '#d8e8ee',
      'porcelain' => '#eff6f8',
      'linen' => '#cee2eb',
      'nude' => '#c1dbe7',
      'rose' => '#7fc3d4',
      'rose-ink' => '#3c677f',
      'champagne' => '#8ec7d6',
      'champagne-ink' => '#40657d',
      'espresso' => '#071e3c',
      'cocoa' => '#124a97',
      'taupe' => '#3263a5',
      'on-rose' => '#071e3c',
      'rose-glow' => '#7fc3d4',
      'rose-card' => '#75b6c8',
      'rose-muted' => '#21425d',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.54)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.56)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.58)',
    ),
  ),
  'vibrant-greens' => 
  array (
    'name' => 'Vibrant Greens',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#e1fcad',
      1 => '#122023',
      2 => '#1e1e1f',
      3 => '#e9e9e9',
      4 => '#d4d5d5',
    ),
    'slots' => 
    array (
      'ivory' => '#e9e9e9',
      'porcelain' => '#f6f6f6',
      'linen' => '#e0e0e0',
      'nude' => '#d4d5d5',
      'rose' => '#e1fcad',
      'rose-ink' => '#54664f',
      'champagne' => '#e4f5c2',
      'champagne-ink' => '#556456',
      'espresso' => '#122023',
      'cocoa' => '#1e1e1f',
      'taupe' => '#636364',
      'on-rose' => '#122023',
      'rose-glow' => '#e1fcad',
      'rose-card' => '#d0eaa2',
      'rose-muted' => '#54664f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.68)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.68)',
    ),
  ),
  'warm-neutrals' => 
  array (
    'name' => 'Warm Neutrals',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#51301f',
      1 => '#7a3110',
      2 => '#aa8867',
      3 => '#fff3db',
      4 => '#eee0c8',
    ),
    'slots' => 
    array (
      'ivory' => '#fff3db',
      'porcelain' => '#fffaf1',
      'linen' => '#f7ead2',
      'nude' => '#eee0c8',
      'rose' => '#aa8867',
      'rose-ink' => '#856349',
      'champagne' => '#cbb195',
      'champagne-ink' => '#82644e',
      'espresso' => '#51301f',
      'cocoa' => '#7a3110',
      'taupe' => '#975c3d',
      'on-rose' => '#392216',
      'rose-glow' => '#cab193',
      'rose-card' => '#a18061',
      'rose-muted' => '#392216',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'champagne: lightened for text on dark surfaces (push 0.06)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.60)',
      3 => 'on-rose: label pushed to read on the accent (push 0.30)',
      4 => 'rose-glow: accent lightened for text on dark surfaces (push 0.38)',
    ),
  ),
  'maroon-mood' => 
  array (
    'name' => 'Maroon Mood',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#262626',
      1 => '#575757',
      2 => '#7a3b3b',
      3 => '#f8f5f5',
      4 => '#e5e2e2',
    ),
    'slots' => 
    array (
      'ivory' => '#f8f5f5',
      'porcelain' => '#fcfbfb',
      'linen' => '#efecec',
      'nude' => '#e5e2e2',
      'rose' => '#f8f5f5',
      'rose-ink' => '#696868',
      'champagne' => '#f8f5f5',
      'champagne-ink' => '#696868',
      'espresso' => '#262626',
      'cocoa' => '#7a3b3b',
      'taupe' => '#915c5c',
      'on-rose' => '#262626',
      'rose-glow' => '#f8f5f5',
      'rose-card' => '#e7e4e4',
      'rose-muted' => '#656464',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.68)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.68)',
    ),
  ),
  'bold-orange' => 
  array (
    'name' => 'Bold Orange',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#ff5c00',
      1 => '#3e2407',
      2 => '#796758',
      3 => '#f7f0e8',
      4 => '#e5dcd2',
    ),
    'slots' => 
    array (
      'ivory' => '#f7f0e8',
      'porcelain' => '#fcf9f6',
      'linen' => '#efe7de',
      'nude' => '#e5dcd2',
      'rose' => '#ff5c00',
      'rose-ink' => '#b24603',
      'champagne' => '#fc9051',
      'champagne-ink' => '#99582b',
      'espresso' => '#3e2407',
      'cocoa' => '#776455',
      'taupe' => '#776455',
      'on-rose' => '#3e2407',
      'rose-glow' => '#fd8038',
      'rose-card' => '#f05801',
      'rose-muted' => '#3e2407',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'cocoa: depth darkened to read as text (push 0.04)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.40)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.52)',
      3 => 'rose-glow: accent lightened for text on dark surfaces (push 0.24)',
    ),
  ),
  'cool-blues' => 
  array (
    'name' => 'Cool Blues',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0d1e21',
      1 => '#2d464b',
      2 => '#899da0',
      3 => '#d8e6e8',
      4 => '#c4d2d4',
    ),
    'slots' => 
    array (
      'ivory' => '#dae8e9',
      'porcelain' => '#f0f6f6',
      'linen' => '#d0dee0',
      'nude' => '#c4d2d4',
      'rose' => '#899da0',
      'rose-ink' => '#506366',
      'champagne' => '#a5b7b9',
      'champagne-ink' => '#506164',
      'espresso' => '#0d1e21',
      'cocoa' => '#2d464b',
      'taupe' => '#4c6367',
      'on-rose' => '#0d1e21',
      'rose-glow' => '#899da0',
      'rose-card' => '#7f9396',
      'rose-muted' => '#192b2e',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.06)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.46)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.56)',
    ),
  ),
  'minimal-neutrals' => 
  array (
    'name' => 'Minimal Neutrals',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#101014',
      1 => '#3d3d47',
      2 => '#d0d1db',
      3 => '#e6e6e6',
      4 => '#d1d1d1',
    ),
    'slots' => 
    array (
      'ivory' => '#e6e6e6',
      'porcelain' => '#f5f5f5',
      'linen' => '#dddddd',
      'nude' => '#d1d1d1',
      'rose' => '#d0d1db',
      'rose-ink' => '#616168',
      'champagne' => '#d8d8df',
      'champagne-ink' => '#606065',
      'espresso' => '#101014',
      'cocoa' => '#3d3d47',
      'taupe' => '#5f5f67',
      'on-rose' => '#101014',
      'rose-glow' => '#d0d1db',
      'rose-card' => '#c1c2cb',
      'rose-muted' => '#4d4e54',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.58)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.60)',
    ),
  ),
  'vibrant-blues' => 
  array (
    'name' => 'Vibrant Blues',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#002846',
      1 => '#5eb2f2',
      2 => '#567790',
      3 => '#baddef',
      4 => '#a7cbde',
    ),
    'slots' => 
    array (
      'ivory' => '#d1e9f4',
      'porcelain' => '#edf6fb',
      'linen' => '#bedcea',
      'nude' => '#a7cbde',
      'rose' => '#5eb2f2',
      'rose-ink' => '#27628e',
      'champagne' => '#7ec1f1',
      'champagne-ink' => '#306287',
      'espresso' => '#002846',
      'cocoa' => '#3e617b',
      'taupe' => '#3e617b',
      'on-rose' => '#002846',
      'rose-glow' => '#5eb2f2',
      'rose-card' => '#56a7e4',
      'rose-muted' => '#0b395b',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.34)',
      1 => 'cocoa: depth darkened to read as text (push 0.28)',
      2 => 'rose-ink: accent darkened for text on light surfaces (push 0.58)',
      3 => 'champagne-ink: darkened for text on light surfaces (push 0.62)',
    ),
  ),
  'power-purple' => 
  array (
    'name' => 'Power Purple',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#312335',
      1 => '#5b2655',
      2 => '#f2d0c4',
      3 => '#ebe7e0',
      4 => '#d8d3cf',
    ),
    'slots' => 
    array (
      'ivory' => '#ebe7e0',
      'porcelain' => '#f7f5f3',
      'linen' => '#e2ded8',
      'nude' => '#d8d3cf',
      'rose' => '#f2d0c4',
      'rose-ink' => '#6f5a63',
      'champagne' => '#f0d8ce',
      'champagne-ink' => '#6e5d66',
      'espresso' => '#312335',
      'cocoa' => '#5b2655',
      'taupe' => '#7e5476',
      'on-rose' => '#312335',
      'rose-glow' => '#f2d0c4',
      'rose-card' => '#e3c2b9',
      'rose-muted' => '#5f4d57',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.68)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.68)',
    ),
  ),
  'classic-neutrals' => 
  array (
    'name' => 'Classic Neutrals',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#243d0f',
      1 => '#b1af9e',
      2 => '#c2c2c2',
      3 => '#d4d3d1',
      4 => '#3d5229',
    ),
    'slots' => 
    array (
      'ivory' => '#e5e5e3',
      'porcelain' => '#f5f5f4',
      'linen' => '#e3e3e1',
      'nude' => '#e1e1df',
      'rose' => '#b1af9e',
      'rose-ink' => '#5a6845',
      'champagne' => '#bdbcb0',
      'champagne-ink' => '#586846',
      'espresso' => '#243d0f',
      'cocoa' => '#3d5229',
      'taupe' => '#586a47',
      'on-rose' => '#243d0f',
      'rose-glow' => '#b3b1a1',
      'rose-card' => '#a6a693',
      'rose-muted' => '#273f12',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.40)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.62)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.66)',
      3 => 'rose-glow: accent lightened for text on dark surfaces (push 0.04)',
    ),
  ),
  'earth-tones' => 
  array (
    'name' => 'Earth Tones',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#8e9867',
      1 => '#e1937d',
      2 => '#f8f3ec',
      3 => '#8d6959',
      4 => '#2a201b',
    ),
    'slots' => 
    array (
      'ivory' => '#f8f3ec',
      'porcelain' => '#fcfaf7',
      'linen' => '#f2eee5',
      'nude' => '#ebe8dc',
      'rose' => '#e1937d',
      'rose-ink' => '#906052',
      'champagne' => '#e9b5a4',
      'champagne-ink' => '#82655a',
      'espresso' => '#2a201b',
      'cocoa' => '#876555',
      'taupe' => '#876555',
      'on-rose' => '#2a201b',
      'rose-glow' => '#e1937d',
      'rose-card' => '#d28a75',
      'rose-muted' => '#402e27',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'cocoa: depth darkened to read as text (push 0.06)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.44)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.54)',
    ),
  ),
  'serene-coastline' => 
  array (
    'name' => 'Serene Coastline',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#b7ccc8',
      1 => '#27818a',
      2 => '#99c0d1',
      3 => '#d0d0d2',
      4 => '#0a2023',
    ),
    'slots' => 
    array (
      'ivory' => '#e5e5e6',
      'porcelain' => '#f5f5f5',
      'linen' => '#d0dad9',
      'nude' => '#b7ccc8',
      'rose' => '#99c0d1',
      'rose-ink' => '#46636c',
      'champagne' => '#acc6d1',
      'champagne-ink' => '#4b6269',
      'espresso' => '#0a2023',
      'cocoa' => '#1f686f',
      'taupe' => '#1f686f',
      'on-rose' => '#0a2023',
      'rose-glow' => '#99c0d1',
      'rose-card' => '#8eb3c3',
      'rose-muted' => '#294349',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.44)',
      1 => 'cocoa: depth darkened to read as text (push 0.26)',
      2 => 'rose-ink: accent darkened for text on light surfaces (push 0.58)',
      3 => 'champagne-ink: darkened for text on light surfaces (push 0.60)',
    ),
  ),
  'sunset-glow' => 
  array (
    'name' => 'Sunset Glow',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#ff9f1a',
      1 => '#f1b864',
      2 => '#c89779',
      3 => '#e7d2bf',
      4 => '#1e1712',
    ),
    'slots' => 
    array (
      'ivory' => '#f0e3d7',
      'porcelain' => '#f9f4ef',
      'linen' => '#f0e1d1',
      'nude' => '#f0dec9',
      'rose' => '#ff9f1a',
      'rose-ink' => '#8a5816',
      'champagne' => '#f7b154',
      'champagne-ink' => '#825e30',
      'espresso' => '#1e1712',
      'cocoa' => '#7d5f4c',
      'taupe' => '#7d5f4c',
      'on-rose' => '#1e1712',
      'rose-glow' => '#ff9f1a',
      'rose-card' => '#ed9419',
      'rose-muted' => '#543814',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.38)',
      1 => 'cocoa: depth darkened to read as text (push 0.44)',
      2 => 'rose-ink: accent darkened for text on light surfaces (push 0.52)',
      3 => 'champagne-ink: darkened for text on light surfaces (push 0.54)',
    ),
  ),
  'dreamy-pastel' => 
  array (
    'name' => 'Dreamy Pastel',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#eba0a0',
      1 => '#edc999',
      2 => '#e5e7a4',
      3 => '#b6e3a8',
      4 => '#231818',
    ),
    'slots' => 
    array (
      'ivory' => '#e7e9ab',
      'porcelain' => '#f5f6dd',
      'linen' => '#d1e6aa',
      'nude' => '#b6e3a8',
      'rose' => '#edc999',
      'rose-ink' => '#705b49',
      'champagne' => '#ead49d',
      'champagne-ink' => '#6f5f4b',
      'espresso' => '#231818',
      'cocoa' => '#7f5757',
      'taupe' => '#7f5757',
      'on-rose' => '#231818',
      'rose-glow' => '#edc999',
      'rose-card' => '#ddbb8f',
      'rose-muted' => '#5c4a3c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'ivory: paper lightened to a light base (push 0.08)',
      1 => 'cocoa: depth darkened to read as text (push 0.54)',
      2 => 'rose-ink: accent darkened for text on light surfaces (push 0.62)',
      3 => 'champagne-ink: darkened for text on light surfaces (push 0.62)',
    ),
  ),
  'aegean-blue-white' => 
  array (
    'name' => 'Aegean Blue & White',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0d3b66',
      1 => '#1d70a2',
      2 => '#6fb7d6',
      3 => '#f4f7f8',
      4 => '#d8d2c4',
    ),
    'slots' => 
    array (
      'ivory' => '#f4f7f8',
      'porcelain' => '#fbfcfc',
      'linen' => '#edf3f6',
      'nude' => '#e4eff4',
      'rose' => '#1d70a2',
      'rose-ink' => '#1d70a2',
      'champagne' => '#92b9d1',
      'champagne-ink' => '#477193',
      'espresso' => '#0c3962',
      'cocoa' => '#557085',
      'taupe' => '#557085',
      'on-rose' => '#f4f7f8',
      'rose-glow' => '#91b9d0',
      'rose-card' => '#2e7ba9',
      'rose-muted' => '#f4f7f8',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'espresso: ink darkened to a dark base (push 0.04)',
      1 => 'cocoa: depth darkened to read as text (push 0.64)',
      2 => 'champagne: lightened for text on dark surfaces (push 0.30)',
      3 => 'champagne-ink: darkened for text on light surfaces (push 0.56)',
      4 => 'rose-glow: accent lightened for text on dark surfaces (push 0.54)',
    ),
  ),
  'cycladic-cobalt' => 
  array (
    'name' => 'Cycladic Cobalt',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#082c4c',
      1 => '#0057a6',
      2 => '#2f80c9',
      3 => '#e9f2f7',
      4 => '#c8d4da',
    ),
    'slots' => 
    array (
      'ivory' => '#e9f2f7',
      'porcelain' => '#f6fafc',
      'linen' => '#dae5ea',
      'nude' => '#c8d4da',
      'rose' => '#2f80c9',
      'rose-ink' => '#2468a6',
      'champagne' => '#70a8d9',
      'champagne-ink' => '#3a6890',
      'espresso' => '#082c4c',
      'cocoa' => '#0057a6',
      'taupe' => '#1767ae',
      'on-rose' => '#041321',
      'rose-glow' => '#72a9da',
      'rose-card' => '#2c77bc',
      'rose-muted' => '#041321',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.28)',
      1 => 'champagne-ink: darkened for text on light surfaces (push 0.52)',
      2 => 'on-rose: label pushed to read on the accent (push 0.56)',
      3 => 'rose-glow: accent lightened for text on dark surfaces (push 0.36)',
    ),
  ),
  'mediterranean-sea-glass' => 
  array (
    'name' => 'Mediterranean Sea Glass',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#123b46',
      1 => '#2a7c83',
      2 => '#64b6ac',
      3 => '#ddefea',
      4 => '#f5f1e8',
    ),
    'slots' => 
    array (
      'ivory' => '#f5f1e8',
      'porcelain' => '#fbf9f6',
      'linen' => '#eaf0e9',
      'nude' => '#ddefea',
      'rose' => '#64b6ac',
      'rose-ink' => '#387475',
      'champagne' => '#97cbc1',
      'champagne-ink' => '#457275',
      'espresso' => '#123b46',
      'cocoa' => '#28777e',
      'taupe' => '#28777e',
      'on-rose' => '#123b46',
      'rose-glow' => '#78beb4',
      'rose-card' => '#5daca4',
      'rose-muted' => '#123b46',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'cocoa: depth darkened to read as text (push 0.08)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.54)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.62)',
      3 => 'rose-glow: accent lightened for text on dark surfaces (push 0.14)',
    ),
  ),
  'greek-terracotta' => 
  array (
    'name' => 'Greek Terracotta',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#153a5b',
      1 => '#2e6f95',
      2 => '#c96f4a',
      3 => '#d8be91',
      4 => '#f3ebdd',
    ),
    'slots' => 
    array (
      'ivory' => '#f3ebdd',
      'porcelain' => '#faf7f1',
      'linen' => '#f2e9d9',
      'nude' => '#f0e6d4',
      'rose' => '#c96f4a',
      'rose-ink' => '#8c5d50',
      'champagne' => '#dca78c',
      'champagne-ink' => '#696870',
      'espresso' => '#153a5b',
      'cocoa' => '#2e6f95',
      'taupe' => '#2e6f95',
      'on-rose' => '#0c2235',
      'rose-glow' => '#dca88e',
      'rose-card' => '#ba6948',
      'rose-muted' => '#0c2235',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'rose-ink: accent darkened for text on light surfaces (push 0.34)',
      1 => 'champagne: lightened for text on dark surfaces (push 0.16)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.58)',
      3 => 'on-rose: label pushed to read on the accent (push 0.42)',
      4 => 'rose-glow: accent lightened for text on dark surfaces (push 0.46)',
    ),
  ),
  'olive-limestone' => 
  array (
    'name' => 'Olive & Limestone',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#26382a',
      1 => '#5e7447',
      2 => '#a99a6f',
      3 => '#d8d0bb',
      4 => '#f2eee4',
    ),
    'slots' => 
    array (
      'ivory' => '#f2eee4',
      'porcelain' => '#faf8f4',
      'linen' => '#e6e1d2',
      'nude' => '#d8d0bb',
      'rose' => '#a99a6f',
      'rose-ink' => '#62654a',
      'champagne' => '#c3b798',
      'champagne-ink' => '#5f6652',
      'espresso' => '#26382a',
      'cocoa' => '#556a42',
      'taupe' => '#556a42',
      'on-rose' => '#253729',
      'rose-glow' => '#bbae8b',
      'rose-card' => '#9e9269',
      'rose-muted' => '#253729',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'cocoa: depth darkened to read as text (push 0.16)',
      1 => 'rose-ink: accent darkened for text on light surfaces (push 0.54)',
      2 => 'champagne-ink: darkened for text on light surfaces (push 0.64)',
      3 => 'on-rose: label pushed to read on the accent (push 0.02)',
      4 => 'rose-glow: accent lightened for text on dark surfaces (push 0.24)',
    ),
  ),
  'santorini-sunset' => 
  array (
    'name' => 'Santorini Sunset',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#173b64',
      1 => '#487fb3',
      2 => '#d98c73',
      3 => '#e9b79f',
      4 => '#f5ebdd',
    ),
    'slots' => 
    array (
      'ivory' => '#f5ebdd',
      'porcelain' => '#fbf7f1',
      'linen' => '#f5e8da',
      'nude' => '#f4e5d6',
      'rose' => '#d98c73',
      'rose-ink' => '#7b646a',
      'champagne' => '#e3ad98',
      'champagne-ink' => '#686776',
      'espresso' => '#163960',
      'cocoa' => '#3b6d9d',
      'taupe' => '#3b6d9d',
      'on-rose' => '#16385e',
      'rose-glow' => '#e0a58f',
      'rose-card' => '#c98571',
      'rose-muted' => '#16385e',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => false,
    ),
    'notes' => 
    array (
      0 => 'espresso: ink darkened to a dark base (push 0.04)',
      1 => 'cocoa: depth darkened to read as text (push 0.26)',
      2 => 'rose-ink: accent darkened for text on light surfaces (push 0.48)',
      3 => 'champagne-ink: darkened for text on light surfaces (push 0.60)',
      4 => 'on-rose: label pushed to read on the accent (push 0.02)',
      5 => 'rose-glow: accent lightened for text on dark surfaces (push 0.26)',
    ),
  ),
);
